export const actionTypes = {
  GET_OOMPALOOMPAS_REQUEST: 'GET_OOMPALOOMPA/REQUEST',
  GET_OOMPALOOMPAS_SUCCESS: 'GET_OOMPALOOMPA/SUCCESS',
  GET_OOMPALOOMPAS_ERROR: 'GET_OOMPALOOMPA/ERROR',
  SET_CURRENTPAGE: 'SET_CURRENTPAGE',
};
