export const actionTypes = {
  GET_OOMPALOOMPAS_REQUEST: 'MAIN/GET_OOMPALOOMPA/REQUEST',
  GET_OOMPALOOMPAS_SUCCESS: 'GET_OOMPALOOMPA/SUCCESS',
  GET_OOMPALOOMPAS_ERROR: 'GET_OOMPALOOMPA/ERROR',
  SET_CURRENTPAGE: 'SET_CURRENTPAGE',
  SET_SELECTED_OOMPALOOMPA: 'MAIN/SET_SELECTED_OOMPALOOMPA',
  GET_SELECTED_OOMPALOOMPA_BY_ID: 'PROFILE/GET_SELECTED_OOMPALOOOMPA_BY_ID',
  SET_OOMPALOOMPA_EXISTS: 'PROFILE/SET_OOMPALOOMPA_EXIST',
  SET_IS_LOADING_INITIALIZATION: 'LOCALSTORAGE/FINISHED_LOADING',
};
