export const actionTypes = {
  GET_LOCALSTORAGE: 'LOCALSTORAGE/GET_LOCALSTORAGE',
  SET_LOCAL_STORAGE_OOMPALOOMPAS_TO_STATE: 'LOCALSTORAGE/SET_LOCAL_STORAGE_OOMPALOOMPAS_TO_STATE',
  SET_LOCAL_STORAGE_PAGENUMBER_TO_STATE: 'LOCALSTORAGE/SET_LOCAL_STORAGE_PAGENUMBER_TO_STATE',
};
